//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WebFresher.MF1773.Demo.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WebFresher.MF1773.Demo.Domain.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmployeeCodeNotFound {
            get {
                return ResourceManager.GetString("EmployeeCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai tài khoản hoặc mật khẩu vui lòng thử lại.
        /// </summary>
        public static string Exception_Account {
            get {
                return ResourceManager.GetString("Exception_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài nguyên bị trùng vui lòng kiểm tra lại.
        /// </summary>
        public static string Exception_Conflict {
            get {
                return ResourceManager.GetString("Exception_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối tới Server.
        /// </summary>
        public static string Exception_ConnectDb {
            get {
                return ResourceManager.GetString("Exception_ConnectDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã bị trùng.
        /// </summary>
        public static string Exception_Duplicate_Customer {
            get {
                return ResourceManager.GetString("Exception_Duplicate_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên &lt;{0}&gt; đã bị trùng.
        /// </summary>
        public static string Exception_Duplicate_Employee {
            get {
                return ResourceManager.GetString("Exception_Duplicate_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống vui lòng liên hệ MiSa để được hỗ trợ.
        /// </summary>
        public static string Exception_Server {
            get {
                return ResourceManager.GetString("Exception_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi người dùng vui lòng nhập lại.
        /// </summary>
        public static string Exception_Valid {
            get {
                return ResourceManager.GetString("Exception_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File nhập khẩu không đúng định dạng cho phép.
        /// </summary>
        public static string ExceptionExtension {
            get {
                return ResourceManager.GetString("ExceptionExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File nhập khẩu không được để trống.
        /// </summary>
        public static string ExceptionNotFile {
            get {
                return ResourceManager.GetString("ExceptionNotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài nguyên.
        /// </summary>
        public static string ExceptionNotFound {
            get {
                return ResourceManager.GetString("ExceptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống.
        /// </summary>
        public static string ExceptionNotNull {
            get {
                return ResourceManager.GetString("ExceptionNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền truy cập.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
    }
}
